### ISSUE TITLE
US 342 - Cadastro de Vagas - Estudos Moodle API docs, Integração Moodle e back-end devit-se

### ISSUE THREAD

**Issue by igords-goncalves** [SouJunior/devit-se-backend#6]
# Task Description

A plataforma de cursos Devit é totalmente construída em cima da plataforma [Moodle ](https://docs.moodle.org/403/en/Main_page) todo nosso processo de integração para obter os dados do aluno Devit para que o mesmo possa se cadastrar em vagas da plataforma Devit-se vagas SouJunior deverá ser feito através de uma integração do back-end e os serviços da Moodle.

## Current US and  links

- https://github.com/SouJunior/products/issues/342

## Checklist
 
- [ ] Estudo de documentação Moodle
- [ ] Criação de serviço de autenticação
- [ ] Consumo de serviço com token gerado na autenticação
- [ ] Requests para o serviço Moodle
- [ ] Manipulação de dados da resposta do request feito
- [ ] Continuidade no andamento da task/issue n. https://github.com/SouJunior/devit-se-backend/issues/3

## Resources

[Moodle official documentation](https://docs.moodle.org/403/en/Main_page)
[Auth example](https://cursos.devit-se.com.br/login/token.php?username=user&password=0LBp4BNbw:Cx&service=moodle_mobile_app) by Carlos
[Response example after consumed service - core_user_get_users_by_field](https://cursos.devit-se.com.br/webservice/rest/server.php?wstoken=9896b18d7a0df3b26c3e3e57daef8eaa&wsfunction=core_user_get_users_by_field&field=username&values[0]=user&moodlewsrestformat=json) by Carlos

**Instruções de uso by Carlos**

![Image](https://github.com/SouJunior/devit-se-backend/assets/79734585/0520835f-ad4c-48a5-8ce1-f9dcb60ff11a)
